services:
  - type: web
    name: facebook-telegram-bot
    runtime: python
    plan: starter
    buildCommand: |
      apt-get update
      apt-get install -y chromium chromium-driver
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: 7791213862:AAFvGyuCCVZqpnQQwjZBbu89drzuiJPAcJM
      - key: ADMIN_USER_IDS
        value: 7791213862
      - key: OWNER_FACEBOOK
        value: https://www.facebook.com/share/168AJz6Ehm/
      - key: DATA_DIR
        value: /tmp/data
    disk:
      name: data
      mountPath: /tmp/data
      sizeGB: 1
