services:
  - type: web
    name: syapa-telegram-bot
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      apt-get update && apt-get install -y $(cat packages.txt)
    startCommand: python telegram_bot.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: TELEGRAM_BOT_TOKEN
        value: 7791213862:AAFvGyuCCVZqpnQQwjZBbu89drzuiJPAcJM
    plan: free
    autoDeploy: true
    healthCheckPath: /
    disk:
      name: data
      mountPath: /data
      sizeGB: 1
